development:
  adapter: postgresql
  encoding: unicode
  database: odc_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: odc_dev_test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: odc
  pool: 5
  username: odc
  password: odc

